//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.296
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UrT_pk3_creator.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UrT_pk3_creator.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die #include &quot;ui/menudef.h&quot;
        ///{
        ///
        ////*	DEFAULT MENU
        ///Revised by woekele for 4.0. Now loads default.cfg, instead of going back to ugly Q3 defaults.
        ///*/
        ///
        ///\\ DEFAULT MENU \\
        ///
        ///menuDef {
        ///    	name &quot;default_menu&quot;
        ///    	visible 0
        ///    	fullscreen 0
        ///    	rect 0 70 490 340
        /////	rect 186 0 443 426
        ///    	focusColor 1 1 1 1
        ///    	style 1
        ///    	border 1
        ///	onOpen { setitemcolor fadebox backcolor 0 0 0 1 ; 
        /////		fadeout fadebox ; 
        ///		show grpdefault ; 
        ///		hide grpfinish }
        ///	onEsc { close default_menu ; close setup_menu ; o [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string _default {
            get {
                return ResourceManager.GetString("_default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die #include &quot;ui/menudef.h&quot;
        ///
        ///{
        ///\\ QUIT CREDIT \\
        ///
        ///  menuDef {
        ///    	name &quot;betacredit&quot;
        ///    	visible 1
        ///    	fullscreen 1
        ///    	background &quot;ui/assets/ut_menuback.jpg&quot;
        ///    	focusColor 1 1 1 1
        ///    	style 1
        ///    	border 1
        ///	onEsc { uiScript &quot;quit&quot; }
        ///	onOpen { setitemcolor next backcolor 0 0 .55 1; setfocus &quot;next&quot; }
        ///
        ///// BLACK TOP BAR    //
        ///itemDef {
        ///	name window
        ///	rect -5 -6 650 76	
        ///	style 1
        ///	border 0
        ///	backcolor 0 0 0 1
        ///	border 1
        ///	bordercolor .5 .5 .5 1
        ///	visible 1
        ///	decoration
        ///	}
        ///// BLACK BOTTOM  [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string betacredit {
            get {
                return ResourceManager.GetString("betacredit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die #include &quot;ui/menudef.h&quot;
        ///
        ///{
        ///\\ QUIT CREDIT \\
        ///
        ///  menuDef {
        ///    	name &quot;betacredit_back&quot;
        ///    	visible 1
        ///    	fullscreen 1
        ///    	background &quot;ui/assets/ut_menuback.jpg&quot;
        ///    	focusColor 1 1 1 1
        ///    	style 1
        ///    	border 1
        ///	onEsc { uiScript &quot;quit&quot; }
        ///	onOpen { setitemcolor previous backcolor 0 0 .55 1; setfocus &quot;previous&quot; }
        ///
        ///// BLACK TOP BAR    //
        ///itemDef {
        ///	name window
        ///	rect -5 -6 650 76	
        ///	style 1
        ///	border 0
        ///	backcolor 0 0 0 1
        ///	border 1
        ///	bordercolor .5 .5 .5 1
        ///	visible 1
        ///	decoration
        ///	}
        /////  [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string betacredit_back {
            get {
                return ResourceManager.GetString("betacredit_back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die #include &quot;ui/menudef.h&quot;
        ///{
        ///
        /////CONNECT MENU
        ///
        ///menuDef {
        ///    name &quot;connect&quot;
        ///	background &quot;ui/assets/backscreen.jpg&quot;
        ///rect 0 0 640 480
        ///    fullScreen 0
        ///    visible 0
        ///    style WINDOW_STYLE_SHADER 
        ///	onopen { }
        ///}
        ///} ähnelt.
        /// </summary>
        internal static string connect {
            get {
                return ResourceManager.GetString("connect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die #include &quot;ui/menudef.h&quot;
        ///{
        ///
        ////*	CONTROLS MENU
        ///Revised by woekele, for 4.0. Slight adjustments, nothing big.
        ///*/
        ///
        ///	menuDef 
        ///	{
        ///    	name &quot;control_menu&quot;
        ///    	visible 0
        ///    	fullscreen 0
        ///    	rect 0 70 490 340
        ///    	focusColor 1 1 1 1
        ///    	style 1
        ///    	border 1
        ///		onClose 
        ///		{
        ///			uiScript saveControls
        ///		}
        ///		onOpen 
        ///		{ 
        ///			setitemcolor fadebox backcolor 0 0 0 1 ; 
        ///			hide grpControls ; 
        ///			show look ; 
        ///			uiScript loadControls 
        ///		}
        ///		
        ///		onEsc 
        ///		{ 
        ///			close control_menu ; 
        ///			close se [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string controls {
            get {
                return ResourceManager.GetString("controls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die #include &quot;ui/menudef.h&quot;
        ///
        ///{
        ///\\ CREATE FAVORITE POPUP MENU \\
        ///
        ///menuDef {
        ///    	name &quot;createfavorite_popmenu&quot;
        ///    	visible 0
        ///    	fullscreen 0
        ///	rect 204 122 235 235
        ///	focusColor 1 1 1 1
        ///    	style 1
        ///    	border 1
        ///	popup
        ///	onopen { setfocus nameEntry }
        ///	onESC { close createfavorite_popmenu ; open joinserver }
        ///
        ///itemdef
        ///	{
        ///	name background
        ///	rect 0 0 235 235
        ///	style WINDOW_STYLE_SHADER
        ///	background &quot;ui/assets/password_bg.jpg&quot;
        ///	border 1
        ///	bordercolor .5 .5 .5 1
        ///	visible 1
        ///	decoration
        ///	}
        ///
        ///  	i [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string createfavorite {
            get {
                return ResourceManager.GetString("createfavorite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die #include &quot;ui/menudef.h&quot;
        ///{
        ///
        ////*ROFL, this needed updating... *kisses* woekele. Removed lots of useless crap and added usefull stuff.
        ///*/
        ///
        ///// SERVER CREATION MENU //
        ///menuDef {
        ///	name &quot;createserver&quot;
        ///	visible 0
        ///	fullscreen 1
        ///	rect 0 0 640 480
        ///	background &quot;ui/assets/ut_menuback.jpg&quot;
        ///	focusColor 1 1 1 1
        ///	style 1
        ///	border 1
        ///	onEsc { close createserver ; open main }
        ///	onOpen { uiScript loadArenas ; hide accept_alt ; show accept ; hide back_alt ; show back }
        ///
        ///
        ///// BLACK TOP BAR //
        ///	itemDef {
        ///		name w [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string createserver {
            get {
                return ResourceManager.GetString("createserver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die #include &quot;ui/menudef.h&quot;
        ///{
        ///
        ////* DEMO MENU
        ///Revised by woekele, started on august 2006 for 4.0. Made the width larger, so long demonames fit.
        ///*/
        ///
        ///// DEMOS //
        ///menuDef {
        ///	name &quot;demo&quot;
        ///	visible 0
        ///	fullscreen 1
        ///	rect 0 0 640 480
        ///	background &quot;ui/assets/ut_menuback.jpg&quot;
        ///	focusColor 1 1 1 1
        ///	style 1
        ///	border 1
        ///	onEsc { close demo ; open main }
        ///	onOpen { uiScript LoadDemos }
        ///
        ///// BLACK TOP BAR //
        ///	itemDef {
        ///		name window
        ///		rect -5 -6 650 76
        ///		style 1
        ///		border 0
        ///		backcolor 0 0 0 1
        ///		border 1
        ///		 [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string demo {
            get {
                return ResourceManager.GetString("demo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die #include &quot;ui/menudef.h&quot;
        ///
        ///{
        ///\\ ERROR MENU		 \\
        ///
        ///menuDef {
        ///	name &quot;error_popmenu&quot;
        ///   	visible 0
        ///   	fullscreen 0
        ///   	rect 170 80 300 320
        ///	focusColor 1 1 1 1
        ///   	style 1
        ///   	border 1
        ///	popup
        ///	onClose { uiScript clearError }
        ///	onOpen { }
        ///	onESC { close error_popmenu ; open main }
        ///
        ///
        ///
        ///itemdef
        ///	{
        ///	name background
        ///	rect 10 15 300 320
        ///	style WINDOW_STYLE_SHADER
        ///	background &quot;ui/assets/serverinfo_bg.jpg&quot;
        ///	border 1
        ///	bordercolor .5 .5 .5 1
        ///	visible 1
        ///	decoration
        ///	}
        ///
        ///  	itemDef {
        ///		name erro [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string error {
            get {
                return ResourceManager.GetString("error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die #include &quot;ui/menudef.h&quot;
        ///
        ///{
        ///// Extra-page menu  //
        ///
        ///  menuDef {
        ///    	name &quot;extra_menu&quot;
        ///    	visible 0
        ///    	fullscreen 1
        ///    	background &quot;ui/assets/ut_menuback.jpg&quot;
        ///    	focusColor 1 1 1 1
        ///    	style 1
        ///    	border 1
        ///	onEsc { close extra_menu; open main }
        ///// BLACK TOP BAR    //
        ///itemDef {
        ///	name window
        ///	rect -5 -6 650 76	
        ///	style 1
        ///	border 0
        ///	backcolor 0 0 0 1
        ///	border 1
        ///	bordercolor .5 .5 .5 1
        ///	visible 1
        ///	decoration
        ///	}
        ///// BLACK BOTTOM BAR    //
        ///itemDef {
        ///	name window
        ///	rect -5 410 650  [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string Extra_Menu {
            get {
                return ResourceManager.GetString("Extra_Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die #include &quot;ui/menudef.h&quot;
        ///
        ///{
        ///\\ Server Information Popup Menu \\
        ///
        ///menuDef {
        ///	name &quot;findplayer_popmenu&quot;
        ///   	visible 0
        ///   	fullscreen 0
        ///   	rect 158 80 320 340
        ///	focusColor 1 1 1 1
        ///   	style 1
        ///   	border 1
        ///	popup
        ///	onClose { }
        ///	onOpen { uiScript FindPlayer ; setfocus namefield }
        ///	onESC { close findplayer_popmenu ; open joinserver }
        ///
        ///
        ///itemdef
        ///	{
        ///	name background
        ///	rect 10 15 300 320
        ///	style WINDOW_STYLE_SHADER
        ///	background &quot;ui/assets/serverinfo_bg.jpg&quot;
        ///	border 1
        ///	bordercolor .5 .5 .5 1
        ///	vis [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string findplayer {
            get {
                return ResourceManager.GetString("findplayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die // Game type info
        /////
        ///// description, g_gametype enum
        /////
        ///
        ///gametypes {
        ///  { &quot;Free For All&quot; 0 }
        ///  { &quot;Team Deathmatch&quot; 3 } 
        ///  { &quot;Team Survivor&quot; 4 }
        ///  { &quot;Follow the Leader&quot; 5 }
        ///  { &quot;Capture and Hold&quot; 6 }
        ///  { &quot;Capture the Flag&quot; 7 }
        ///  { &quot;Bomb Mode&quot; 8 }	
        ///}
        ///
        ///
        ///// english name, map name, vs count, par times per gametype valid gametyes for ui
        ///// 
        ///maps {
        ///
        ///}										  
        ///
        ///joingametypes {
        ///  { &quot;All&quot; -1 }
        ///  { &quot;Free For All&quot; 0 }
        ///  { &quot;Team Deathmatch&quot; 3 } 
        ///  { &quot;Team Survivor&quot; 4 }
        ///  { &quot;Follow the Leade [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string gameinfo {
            get {
                return ResourceManager.GetString("gameinfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die #include &quot;ui/menudef.h&quot;
        ///
        ///// team menu
        ///// 
        ///// defines from ui_shared.h
        ///
        ///{
        ///	assetGlobalDef 
        ///	{
        ///    	cursor &quot;ui/assets/3_cursor3&quot;			// cursor	
        ///    	fadeClamp 1.0					// sets the fadeup alpha
        ///		fadeCycle 1					// how often fade happens in milliseconds
        ///		fadeAmount 0.1					// amount to adjust alpha per cycle
        ///
        ///		shadowX  5					// x amount for shadow offset
        ///		shadowY  5					// y amount for shadow offset
        ///		shadowColor 0.1 0.1 0.1 0.25			// shadow color
        ///
        ///   		font &quot;fonts/font&quot; 16				// font
        ///    	s [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string hud_menu {
            get {
                return ResourceManager.GetString("hud_menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die // hud menu defs
        ///// 
        ///{
        /// 	loadMenu { &quot;ui/hud.menu&quot; }
        /// 	loadMenu { &quot;ui/score.menu&quot; }
        ///	loadMenu { &quot;ui/teamscore.menu&quot; }
        ///} ähnelt.
        /// </summary>
        internal static string hud_txt {
            get {
                return ResourceManager.GetString("hud_txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die #include &quot;ui/menudef.h&quot;
        ///{
        ///
        ////* INGAME ABOUT MENU
        ///Revised by woekele, for 4.0. Contained a lot of stuff that wasn&apos;t showing correct info, removed it.
        ///*/
        ///
        ///menuDef {
        ///    name &quot;ingame_about&quot;
        ///    visible 0
        ///    fullscreen 0
        ///	//outOfBoundsClick	
        ///rect -15 50 256 295
        ///    focusColor 1 1 1 1
        ///    style 1
        ///    border 1
        ///
        ///	itemdef {
        ///		name background
        ///	rect 15 15 265 200
        ///		style WINDOW_STYLE_SHADER
        ///		background &quot;ui/assets/ingame_bg_options_tr.tga&quot;
        ///		border 1
        ///		bordercolor .5 .5 .5 1
        ///		visible 1
        ///		dec [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string ingame_about {
            get {
                return ResourceManager.GetString("ingame_about", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die #include &quot;ui/menudef.h&quot;
        ///
        ///{
        ///\\ ADDBOT MENU \\
        ///
        ///menuDef {
        ///    	name &quot;ingame_addbot&quot;
        ///    	visible 0
        ///    	fullscreen 0
        ///	outOfBoundsClick			// this closes the window if it gets a click out of the rectangle
        ///    	rect 118 30 192 123
        ///	disableColor  .5 .5 .5 1 
        ///    	focusColor 1 1 1 1
        ///    	style 1
        ///    	border 1
        ///
        ///itemdef
        ///	{
        ///	name background
        ///	rect -1 15 172 113
        ///	style WINDOW_STYLE_SHADER
        ///	background &quot;ui/assets/ingame_bg_addbot.jpg&quot;
        ///	border 1
        ///	bordercolor .5 .5 .5 1
        ///	visible 1
        ///	decoration
        ///	}
        /// [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string ingame_addbot {
            get {
                return ResourceManager.GetString("ingame_addbot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die #include &quot;ui/menudef.h&quot;
        ///{
        ///
        ////*	INGAME CALLVOTE MENU
        ///Revised by woekele, for 4.0. Slight adjustments, nothing big.
        ///*/
        ///
        ///\\ CALL VOTE MENU \\
        ///
        ///menuDef {
        ///    	name &quot;ingame_callvote&quot;
        ///    	visible 0
        ///    	fullscreen 0
        ///    	rect 341 50 289 300
        ///	   	focusColor 1 1 1 1
        ///    	style 1
        ///    	border 1
        /////	hehe thnom!
        ///	onopen { hide grpcallVote ; show misc ; uiScript loadArenas }
        /////	onopen { hide grpcallVote ; show misc }
        ///
        ///itemdef
        ///	{
        ///	name background
        ///	rect 0 15 294 300
        ///	style WINDOW_STYLE_SHADER
        ///	bac [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string ingame_callvote {
            get {
                return ResourceManager.GetString("ingame_callvote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die #include &quot;ui/menudef.h&quot;
        ///{
        ///
        ////*	INGAME_CONTROLS MENU
        ///Revised by woekele, for 4.0. Slight adjustments, nothing big. Removed useless crap.
        ///*/
        ///
        ///\\ SETUP MENU \\
        ///
        ///menuDef {
        ///    	name &quot;ingame_controls&quot;
        ///    	visible 0
        ///    	fullscreen 0
        ///    	rect 163 50 375 335
        ///    	focusColor 1 1 1 1
        ///    	style 1
        ///    	border 1
        ///	onClose {
        ///	    uiScript saveControls
        ///	}
        ///	onopen { hide grpControls ; show look ; uiScript loadControls }
        ///
        ///itemdef
        ///	{
        ///	name background
        ///	rect 10 15 355 300
        ///	style WINDOW_STYLE_SHADER        /// [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string ingame_controls {
            get {
                return ResourceManager.GetString("ingame_controls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die #include &quot;ui/menudef.h&quot;
        ///{
        ///
        ////*	INGAME_SELECT_TEAM
        ///Revised by woekele, for 4.0. Slight adjustments, nothing big.
        ///*/
        ///
        ///\\ INGAME_LEAVE MENU \\
        ///
        ///  menuDef {
        ///    	name &quot;ingame_leave&quot;
        ///    	visible 1
        ///    	fullScreen 0
        ///	   	rect 454 50 128 125
        ///	focusColor 1 1 1 1
        ///	onOpen { show grpMenu ; hide grpConfirm }
        ///
        ///itemdef
        ///	{
        ///	name background
        ///     	rect 0 15 128 120   	//      rect indent[left] Width Thickness Height
        ///	style WINDOW_STYLE_SHADER
        ///	background &quot;ui/assets/ingame_bg_options_tr.tga&quot;
        ///	border 1        /// [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string ingame_leave {
            get {
                return ResourceManager.GetString("ingame_leave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die #include &quot;ui/menudef.h&quot;
        ///{
        ///
        ////*	INGAME_SELECT_TEAM
        ///Revised by woekele, for 4.0. Slight adjustments, nothing big.
        ///*/
        ///
        ///  assetGlobalDef {
        ///    	font &quot;fonts/fontImage_0_16&quot; 16				// font
        ///    	smallFont &quot;fonts/fontImage_0_12&quot; 12				// font
        ///    	bigFont &quot;fonts/fontImage_0_20t&quot; 20				// font
        ///	cursor &quot;ui/assets/3_cursor3&quot;			// cursor	
        ///	itemFocusSound &quot;sound/misc/menu2.wav&quot;		// sound for item getting focus (via keyboard or mouse )
        ///	
        ///    	fadeClamp 1.0					// sets the fadeup alpha
        ///	fadeCycle 1					// how [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string ingame_menu {
            get {
                return ResourceManager.GetString("ingame_menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die #include &quot;ui/menudef.h&quot;
        ///{
        ///
        ////* INGAME OPTIONS MENU
        ///New Implementation by woekele, for 4.0. This needed to be redone, badly.
        ///*/
        ///
        /////Standard Menu Creation
        ///
        ///menuDef {
        ///	name &quot;ingame_options&quot;
        ///	visible 0
        ///	//outOfBoundsClick //this closes the window if it gets a click out of the rectangle, pretty annoying, so I commented it out.
        ///rect 200 50 440 340
        ///	focusColor 1 1 1 1
        ///	style 1
        ///	border 1
        ///	onOpen { show general ; hide crosshair ; hide minimap ; hide teaminfo ; hide blood ; hide bullet ; hide chat ; h [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string ingame_options {
            get {
                return ResourceManager.GetString("ingame_options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die #include &quot;ui/menudef.h&quot;
        ///{
        ///
        ////*	INGAME PLAYER MENU
        ///Revised by woekele, for 4.0. Slight adjustments, nothing big.
        ///*/
        ///
        ///\\ INGAME_JOIN MENU \\
        ///
        ///  menuDef {
        ///    	name &quot;ingame_player&quot;
        ///    	visible 1
        ///    	fullScreen 0
        ///	rect 62 50 200 256	//x y z t      x=indentl  y=down z=width of box  t=height
        ///	focusColor 1 1 1 1
        ///
        ///itemdef
        ///	{
        ///	name background
        ///     	rect 0 16 148 160   
        ///	style WINDOW_STYLE_SHADER
        ///	background &quot;ui/assets/ingame_bg_options_tr.tga&quot;
        ///	border 1
        ///	bordercolor .5 .5 .5 1
        ///	visible 1
        ///	d [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string ingame_player {
            get {
                return ResourceManager.GetString("ingame_player", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die #include &quot;ui/menudef.h&quot;
        ///{
        ///
        ////*	INGAME_RCON MENU
        ///Revised by woekele, for 4.0. Slight adjustments, nothing big.
        ///*/
        ///
        ///// RCON OPTIONS	//
        ///
        ///menuDef {
        ///    	name &quot;ingame_rcon&quot;
        ///    	visible 0
        ///    	fullscreen 0
        ///    	rect 391 50 230 300
        ///	   	focusColor 1 1 1 1
        ///    	style 1
        ///    	border 1
        ///
        ///	onopen { hide grpcallVote ; show admin }//; uiScript loadArenas }
        ///
        ///itemdef
        ///	{
        ///	name background
        ///	rect 0 15 230 255
        ///	style WINDOW_STYLE_SHADER
        ///	background &quot;ui/assets/ingame_bg_options_tr.tga&quot;
        ///	border 1
        ///	border [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string ingame_rcon {
            get {
                return ResourceManager.GetString("ingame_rcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die #include &quot;ui/menudef.h&quot;
        ///{
        ///
        ////*	INGAME GEAR MENU
        ///Revised by woekele, for 4.0. Slight adjustments, nothing big. Updated descriptions
        ///*/
        ///
        ///	menuDef
        ///	{
        ///		name &quot;ingame_ut_select_gear&quot;
        ///		visible 0
        ///		fullscreen 0
        ///		rect -5 -5 650 490
        ///		focusColor 1 1 1 1
        ///		disablecolor 0 0 0 0
        ///		backcolor 0 0 0 0
        /// 		style 0
        ///    		border 0
        ///		onEsc { close ingame_ut_select_gear }		
        ///		onOpen { uiScript gearRead }
        ///
        ///
        ///itemdef
        ///	{
        ///	name window
        ///	rect 73 79 494 321
        ///	style WINDOW_STYLE_SHADER
        ///	background &quot;ui/assets/i [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string ingame_select_gear {
            get {
                return ResourceManager.GetString("ingame_select_gear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die #include &quot;ui/menudef.h&quot;
        ///
        ///{
        ///	menuDef
        ///	{
        ///		name &quot;ingame_ut_select_gear_grenade&quot;
        ///		visible 0
        ///		fullscreen 0
        ///		rect -5 -5 650 490
        ///		focusColor 1 1 1 1
        ///		backcolor 0 0 0 0
        /// 		style WINDOW_STYLE_FILLED
        ///    	border 0
        ///		onEsc { close ingame_ut_select_gear_grenade ; 
        ///		open ingame_ut_select_gear }
        ///		
        ///		onOpen { }
        ///
        ///itemdef
        ///	{
        ///	name window
        ///	rect 73 79 494 321
        ///	style WINDOW_STYLE_SHADER
        ///	background &quot;ui/assets/ingame_bg2_tr.tga&quot;
        ///	border 1
        ///	bordercolor .5 .5 .5 1
        ///	visible 1
        ///	decoration
        ///	}
        ///
        ///i [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string ingame_select_gear_grenade {
            get {
                return ResourceManager.GetString("ingame_select_gear_grenade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die #include &quot;ui/menudef.h&quot;
        ///
        ///{
        ///	menuDef
        ///	{
        ///		name &quot;ingame_ut_select_gear_item&quot;
        ///		visible 0
        ///		fullscreen 0
        ///		rect -5 -5 650 490
        ///		focusColor 1 1 1 1
        ///		backcolor 0 0 0 0
        /// 		style WINDOW_STYLE_FILLED
        ///    		border 0
        ///		onEsc 
        ///		{ close ingame_ut_select_gear_item ; 
        ///		open ingame_ut_select_gear }
        ///		
        ///		onOpen { }
        ///
        ///itemdef
        ///	{
        ///	name window
        ///	rect 73 79 494 321
        ///	style WINDOW_STYLE_SHADER
        ///	background &quot;ui/assets/ingame_bg2_tr.tga&quot;
        ///	border 1
        ///	bordercolor .5 .5 .5 1
        ///	visible 1
        ///	decoration
        ///	}
        ///
        ///it [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string ingame_select_gear_item {
            get {
                return ResourceManager.GetString("ingame_select_gear_item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die #include &quot;ui/menudef.h&quot;
        ///
        ///{
        ///	menuDef
        ///	{
        ///		name &quot;ingame_ut_select_gear_primary&quot;
        ///		visible 0
        ///		fullscreen 0
        ///		rect -5 -5 650 490
        ///		focusColor 1 1 1 1
        ///		backcolor 0 0 0 0
        /// 		style WINDOW_STYLE_FILLED
        ///    		border 0
        ///		onEsc { close ingame_ut_select_gear_primary ; 
        ///		open ingame_ut_select_gear }
        ///		
        ///		onOpen { }
        ///
        ///itemdef
        ///	{
        ///	name window
        ///	rect 73 79 494 321
        ///	style WINDOW_STYLE_SHADER
        ///	background &quot;ui/assets/ingame_bg2_tr.tga&quot;
        ///	border 1
        ///	bordercolor .5 .5 .5 1
        ///	visible 1
        ///	decoration
        ///	}
        ///
        /// [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string ingame_select_gear_primary {
            get {
                return ResourceManager.GetString("ingame_select_gear_primary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die #include &quot;ui/menudef.h&quot;
        ///
        ///{
        ///	menuDef
        ///	{
        ///		name &quot;ingame_ut_select_gear_secondary&quot;
        ///		visible 0
        ///		fullscreen 0
        ///		rect -5 -5 650 490
        ///		focusColor 1 1 1 1
        ///		backcolor 0 0 0 0
        /// 		style WINDOW_STYLE_FILLED
        ///    		border 0
        ///		onEsc 
        ///		{ close ingame_ut_select_gear_secondary ; 
        ///		open ingame_ut_select_gear }
        ///		
        ///		onOpen { }
        ///
        ///
        ///itemdef
        ///	{
        ///	name window
        ///	rect 73 79 494 321
        ///	style WINDOW_STYLE_SHADER
        ///	background &quot;ui/assets/ingame_bg2_tr.tga&quot;
        ///	border 1
        ///	bordercolor .5 .5 .5 1
        ///	visible 1
        ///	decorati [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string ingame_select_gear_secondary {
            get {
                return ResourceManager.GetString("ingame_select_gear_secondary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die #include &quot;ui/menudef.h&quot;
        ///
        ///{
        ///	menuDef
        ///	{
        ///		name &quot;ingame_ut_select_gear_sidearm&quot;
        ///		visible 0
        ///		fullscreen 0
        ///		rect -5 -5 650 490
        ///		focusColor 1 1 1 1
        ///		backcolor 0 0 0 0
        /// 		style WINDOW_STYLE_FILLED
        ///    		border 0
        ///		onEsc 
        ///		{ close ingame_ut_select_gear_sidearm ; 
        ///		open ingame_ut_select_gear }
        ///		
        ///		onOpen { }
        ///
        ///
        ///itemdef
        ///	{
        ///	name window
        ///	rect 73 79 494 321
        ///	style WINDOW_STYLE_SHADER
        ///	background &quot;ui/assets/ingame_bg2_tr.tga&quot;
        ///	border 1
        ///	bordercolor .5 .5 .5 1
        ///	visible 1
        ///	decoration
        /// [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string ingame_select_gear_sidearm {
            get {
                return ResourceManager.GetString("ingame_select_gear_sidearm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die #include &quot;ui/menudef.h&quot;
        ///{
        ///
        ////* INGAME SELECT PLAYER MENU
        ///Revised by woekele, for 4.0. Changed the entire lay-out basicly.
        ///*/
        ///
        /////Standard Menu Creation
        ///	
        ///menuDef {
        ///	name &quot;ingame_ut_select_player&quot;
        ///	visible 0
        ///rect 32 50 486 388
        ///	focusColor 1 1 1 1
        /// 	style 1
        ///    border 1
        ///	//outOfBoundsClick
        ///	onEsc 	{ close ingame_ut_select_player }
        ///	onOpen  { uiScript update &quot;ui_GetName&quot; ; setfocus window }
        ///	onClose { uiScript update &quot;ui_SetName&quot; }
        ///
        ///
        ///	itemdef {
        ///		name backgroundstuff
        ///	rect 15 15 456 358
        /// [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string ingame_select_player {
            get {
                return ResourceManager.GetString("ingame_select_player", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die #include &quot;ui/menudef.h&quot;
        ///{
        ///
        ////*	INGAME_SELECT_TEAM
        ///Revised by woekele, for 4.0. Little changes
        ///*/
        ///
        ///	menuDef
        ///	{
        ///		name &quot;ingame_ut_select_team&quot;
        ///		visible 0
        ///		fullscreen 0
        ///		rect -5 -5 650 490
        ///		backcolor 0 0 0 0
        ///		focusColor 1 1 1 1
        ///    		style 0 //1
        ///    		border 0
        ///		bordersize 1
        ///		bordercolor 1 1 1 1
        ///		onEsc 
        ///		{ close ingame_ut_select_team }
        ///		
        ///		onOpen { }
        ///
        ///itemdef
        ///	{
        ///	name window
        ///	rect 73 79 494 321
        ///	style WINDOW_STYLE_SHADER
        ///	background &quot;ui/assets/ingame_bg2_tr.tga&quot;
        ///	border 1        /// [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string ingame_select_team {
            get {
                return ResourceManager.GetString("ingame_select_team", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die #include &quot;ui/menudef.h&quot;
        ///{	
        ///
        ////* INGAME STATS MENU
        ///Created by woekele. Twentyseven demanded this from me, so I had no choice :(
        ///*/
        ///
        ///menuDef {
        ///	name &quot;ingame_stats&quot;
        ///	visible 0
        ///	rect 0 40 640 440
        ///	focusColor 1 1 1 1
        ///	style 1
        ///	border 0
        ///	onOpen { uiScript getStats }
        ///	onEsc { close ingame_stats }
        ///
        ///	itemdef {
        ///		name background
        ///		rect 0 0 640 300
        ///		style WINDOW_STYLE_SHADER
        ///		background &quot;ui/assets/ingame_bg2_tr.tga&quot;
        ///		border 0
        ///		bordercolor .5 .5 .5 1
        ///		visible 1
        ///		decoration
        ///		
        ///	}
        ///
        ///	item [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string ingame_stats {
            get {
                return ResourceManager.GetString("ingame_stats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die #include &quot;ui/menudef.h&quot;
        ///{
        ///
        ////* INGAME SYSTEM MENU
        ///Revised by woekele, for 4.0. Removed some useless crap and added usefull stuff.
        ///*/
        ///
        /////Standard Menu Creation
        ///
        ///
        ///menuDef {
        ///	name &quot;ingame_system&quot;
        ///	visible 0
        ///rect 256 50 384 430
        ///	focusColor 1 1 1 1
        ///	style 1
        ///	border 1
        ///	onOpen { show graphics ; hide sound ; hide network }
        ///
        ///	itemdef {
        ///		name backgroundstuff
        ///	rect 15 15 359 370
        ///		style WINDOW_STYLE_SHADER
        ///		background &quot;ui/assets/ingame_bg_options_tr.tga&quot;
        ///		border 1
        ///		bordercolor .5 .5 .5 1
        ///	 [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string ingame_system {
            get {
                return ResourceManager.GetString("ingame_system", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die // menu defs
        ///{
        ///	loadMenu { &quot;ui/ingame.menu&quot; }
        ///	loadMenu { &quot;ui/ingame_about.menu&quot; }
        ///	loadMenu { &quot;ui/ingame_controls.menu&quot; }
        ///	loadMenu { &quot;ui/ingame_options.menu&quot; }
        ///	loadMenu { &quot;ui/ingame_rcon.menu&quot; }
        ///	loadMenu { &quot;ui/ingame_system.menu&quot; }
        ///	loadMenu { &quot;ui/ingame_leave.menu&quot; }
        ///	loadMenu { &quot;ui/ingame_player.menu&quot; }
        ///	loadMenu { &quot;ui/ingame_stats.menu&quot; }					//new statsthing: woekwoek
        ///	loadMenu { &quot;ui/ingame_callvote.menu&quot; }
        ///	loadMenu { &quot;ui/ingame_vote.menu&quot; }
        ///	loadMenu { &quot;ui/ingame_select_team.menu&quot; }
        /// [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string ingame_txt {
            get {
                return ResourceManager.GetString("ingame_txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die #include &quot;ui/menudef.h&quot;
        ///{
        ///
        ////*	INGAME MATCHMODE MENU
        ///Revised by woekele, for 4.0. Slight adjustments, nothing big.
        ///*/
        ///
        ///menuDef {
        ///    	name &quot;ingame_ut_matchmode&quot;
        ///    	visible 0
        ///    	fullscreen 0
        ///    	rect 59 50 140 240
        ///	//outOfBoundsClick
        ///    	focusColor 1 1 1 1
        ///    	style 1
        ///    	border 1
        ///	//onOpen { close &quot;ingame_options&quot; ; show match ; uiScript loadArenas }
        ///	onOpen { close &quot;ingame_options&quot; ; show match }
        ///
        ///itemdef
        ///	{
        ///	name background
        ///	rect 0 15 154 139
        ///	style WINDOW_STYLE_SHADER
        ///	back [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string ingame_ut_matchmode {
            get {
                return ResourceManager.GetString("ingame_ut_matchmode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die #include &quot;ui/menudef.h&quot;
        ///
        ///{
        ///\\ SERVER INFO MENU \\
        ///
        ///menuDef {
        /// 	name &quot;ingame_vote&quot;
        /// 	visible 0
        /// 	fullscreen 0
        ///	outOfBoundsClick			// this closes the window if it gets a click out of the rectangle
        ///  	rect 398 31 100 145
        ///  	focusColor 1 1 1 1
        ///  	style 1
        ///
        ///	itemdef
        ///		{
        ///		name background
        ///		rect 0 15 100 75 
        ///		style WINDOW_STYLE_SHADER
        ///		background &quot;ui/assets/ingame_bg_leave.jpg&quot;
        ///		border 1
        ///		bordercolor .5 .5 .5 1
        ///		visible 1
        ///		decoration
        ///	}
        ///
        ///
        /////  BUTTONS	//
        ///
        ///
        ///	itemDef {
        ///		name yes        /// [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string ingame_vote {
            get {
                return ResourceManager.GetString("ingame_vote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die #include &quot;ui/menudef.h&quot;
        ///{
        ///
        ////*  SERVERBROWSER
        ///Revised by woekele, for 4.0. Changed some little things. Added the PB-filter
        ///*/
        ///
        ///menuDef {
        ///	name &quot;joinserver&quot;
        ///	visible 0
        ///	fullscreen 1
        ///	rect 0 0 640 480
        ///	background &quot;ui/assets/ut_menuback.jpg&quot;
        ///	focusColor 1 1 1 1
        ///	//outOfBoundsClick	
        ///	style 1
        ///	border 1
        ///	onOpen { uiScript UpdateFilter; }
        ///	onEsc { uiScript closeJoin }
        ///
        ///// BLACK TOP BAR //
        ///	itemDef {
        ///		name window
        ///		rect -5 -6 650 76
        ///		style 1
        ///		border 0
        ///		backcolor 0 0 0 1
        ///		border 1
        ///		b [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string joinserver {
            get {
                return ResourceManager.GetString("joinserver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die #include &quot;ui/menudef.h&quot;
        ///{
        ///
        ////*	MAIN MENU
        ///Revised by woekele, for 4.0. Slight adjustments, nothing big.
        ///*/
        ///
        ///assetGlobalDef {
        ///	//font &quot;fonts/font&quot; 16
        ///	//font &quot;fonts/fontImage_0_16&quot; 16
        ///	//smallFont &quot;fonts/smallfont&quot; 12
        ///	//font &quot;fonts/fontImage_0_12&quot; 12
        ///	//bigFont &quot;fonts/bigfont&quot; 20
        ///	//font &quot;fonts/fontImage_0_20&quot; 20
        ///	cursor &quot;ui/assets/3_cursor3.tga&quot;		// cursor
        ///	itemFocusSound &quot;sound/misc/menu2.wav&quot;	// sound for item getting focus (via keyboard or mouse )
        ///	
        ///	fadeClamp 1.0							// sets the fadeup [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string Main_Menu {
            get {
                return ResourceManager.GetString("Main_Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die #define ITEM_TYPE_TEXT 0                  // simple text
        ///#define ITEM_TYPE_BUTTON 1                // button, basically text with a border 
        ///#define ITEM_TYPE_RADIOBUTTON 2           // toggle button, may be grouped 
        ///#define ITEM_TYPE_CHECKBOX 3              // check box
        ///#define ITEM_TYPE_EDITFIELD 4             // editable text, associated with a cvar
        ///#define ITEM_TYPE_COMBO 5                 // drop down list
        ///#define ITEM_TYPE_LISTBOX 6               // scrollable list  
        ///#define ITEM_TYPE_MODEL 7    [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string menudef {
            get {
                return ResourceManager.GetString("menudef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die // menu defs
        ///{	
        ///	loadMenu { &quot;ui/extra.menu&quot; }
        ///	loadMenu { &quot;ui/main.menu&quot; }
        ///	loadMenu { &quot;ui/joinserver.menu&quot; }
        ///	loadMenu { &quot;ui/setup.menu&quot; }
        ///	loadMenu { &quot;ui/createserver.menu&quot; }
        ///	loadMenu { &quot;ui/controls.menu&quot; }
        ///	loadMenu { &quot;ui/system.menu&quot; }
        ///	loadMenu { &quot;ui/options.menu&quot; }
        ///	loadMenu { &quot;ui/connect.menu&quot; }
        ///	loadMenu { &quot;ui/password.menu&quot; }
        ///	loadMenu { &quot;ui/vid_restart.menu&quot; }
        ///	loadMenu { &quot;ui/default.menu&quot; }
        ///	loadMenu { &quot;ui/error.menu&quot; }
        ///	loadMenu { &quot;ui/serverinfo.menu&quot; }
        ///	loadMenu { &quot;ui/findplaye [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string Menus {
            get {
                return ResourceManager.GetString("Menus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die #include &quot;ui/menudef.h&quot;
        ///{
        ///
        ////* GAME OPTIONS MENU
        ///New Implementation by woekele, started on august 2006 for 4.0. This needed to be redone, badly.
        ///*/
        ///
        /////Standard Menu Creation
        ///
        ///menuDef {
        ///	name &quot;options_menu&quot;
        ///    visible 0
        ///rect 0 70 490 340
        ///    focusColor 1 1 1 1
        ///    style 1
        ///	border 1
        ///	onOpen { show general ; hide crosshair ; hide minimap ; hide teaminfo ; hide blood ; hide bullet ; hide chat ; hide gun ; hide punkbuster }
        ///	onEsc { close options_menu ; close setup_menu ; open main }
        ///
        ///	itemDef [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string options {
            get {
                return ResourceManager.GetString("options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die #include &quot;ui/menudef.h&quot;
        ///
        ///{
        ///\\ PASSWORD POPUP MENU \\
        ///
        ///menuDef {
        ///	name &quot;password_popmenu&quot;
        ///    	visible 0
        ///    	fullscreen 0
        ///	rect 204 122 235 235
        ///	focusColor 1 1 1 1
        ///    	style 1
        ///    	border 1
        ///	popup
        ///	onopen { setfocus passwordEntry }
        ///	onESC { close password_popmenu ; open joinserver }
        ///
        ///itemdef
        ///	{
        ///	name background
        ///	rect 0 0 235 235
        ///	style WINDOW_STYLE_SHADER
        ///	background &quot;ui/assets/password_bg.jpg&quot;
        ///	border 1
        ///	bordercolor .5 .5 .5 1
        ///	visible 1
        ///	decoration
        ///	}
        ///
        ///  	itemDef {
        ///		name se [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string password {
            get {
                return ResourceManager.GetString("password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die #include &quot;ui/menudef.h&quot;
        ///{
        ///
        ////*  PLAYER MENU
        ///Revised by woekele, for 4.0. Changed the entire lay-out basicly. The player-select thingy is kind of a HACK :/ Couldn&apos;t find a better way.
        ///*/
        ///
        /////Standard Menu Creation
        ///
        ///menuDef {
        ///    name &quot;psetup_menu&quot;
        ///    visible 0
        ///    fullscreen 0
        ///rect 0 70 490 340
        ///    focusColor 1 1 1 1
        ///    style 1
        ///    border 1
        ///	onEsc { close psetup_menu ; close setup_menu ; open main ; uiScript update &quot;ui_SetName&quot; }
        ///	onOpen  { uiScript update &quot;ui_GetName&quot; ; setfocus window }
        /// [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string psetup {
            get {
                return ResourceManager.GetString("psetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die #include &quot;ui/menudef.h&quot;
        ///
        ///{
        ///\\ QUIT CREDIT \\
        ///
        ///  menuDef {
        ///    	name &quot;quitCredit&quot;
        ///    	visible 0
        ///    	fullscreen 1
        ///    	background &quot;ui/assets/ut_menuback.jpg&quot;
        ///    	focusColor 1 1 1 1
        ///    	style 1
        ///    	border 1
        ///	onEsc { uiScript &quot;quit&quot; }
        ///	onOpen { setitemcolor previous backcolor 0 0 0 1; setitemcolor next backcolor 0 0 0 1 }
        ///// BLACK TOP BAR    //
        ///itemDef {
        ///	name window
        ///	rect -5 -6 650 76	
        ///	style 1
        ///	border 0
        ///	backcolor 0 0 0 1
        ///	border 1
        ///	bordercolor .5 .5 .5 1
        ///	visible 1
        ///	decoration
        /// [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string quitcredit {
            get {
                return ResourceManager.GetString("quitcredit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die #include &quot;ui/menudef.h&quot;
        ///
        ///{
        ///\\ QUIT CREDIT \\
        ///
        ///  menuDef {
        ///    	name &quot;quitCredit_back&quot;
        ///    	visible 0
        ///    	fullscreen 1
        ///    	background &quot;ui/assets/ut_menuback.jpg&quot;
        ///    	focusColor 1 1 1 1
        ///    	style 1
        ///    	border 1
        ///	onEsc { uiScript &quot;quit&quot; }
        ///	onOpen { setitemcolor previous backcolor 0 0 .55 1; setfocus &quot;previous&quot; }
        ///
        ///// BLACK TOP BAR    //
        ///itemDef {
        ///	name window
        ///	rect -5 -6 650 76	
        ///	style 1
        ///	border 0
        ///	backcolor 0 0 0 1
        ///	border 1
        ///	bordercolor .5 .5 .5 1
        ///	visible 1
        ///	decoration
        ///	}
        /////  [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string quitcredit_back {
            get {
                return ResourceManager.GetString("quitcredit_back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die #include &quot;ui/menudef.h&quot;
        ///
        ///{
        ///\\ score_menu \\
        ///
        ///  menuDef {
        ///    	name &quot;score_menu&quot;
        ///    	visible 0
        ///    	fullscreen 0
        ///    	rect 0 0 640 480
        ///    	focusColor 1 1 1 1
        ///    	style 0
        ///    	border 1
        ///
        ///
        ///// GAMETYPE BAR	//
        ///
        ///itemDef {
        ///	name background
        ///	rect 110 10 420 458 
        ///	style WINDOW_STYLE_FILLED
        ///	border 1
        ///	bordercolor .5 .5 .5 1
        ///	forecolor 1 1 1 1
        ///	backcolor 0 0 0 .8
        ///	visible 1
        ///	decoration
        ///	}
        ///
        ///itemDef {
        ///      	name topbar
        ///      	style WINDOW_STYLE_SHADER
        ///      	background &quot;ui/assets/ingam [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string score {
            get {
                return ResourceManager.GetString("score", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die #include &quot;ui/menudef.h&quot;
        ///
        ///{
        ///\\ Server Information Popup Menu \\
        ///
        ///menuDef {
        ///	name &quot;serverinfo_popmenu&quot;
        ///   	visible 0
        ///   	fullscreen 0
        ///   	rect 158 80 320 340
        ///	focusColor 1 1 1 1
        ///   	style 1
        ///   	border 1
        ///	popup
        ///	onClose { }
        ///	onOpen { uiScript ServerStatus }
        ///	onESC { close serverinfo_popmenu ; open joinserver }
        ///
        ///itemdef
        ///	{
        ///	name background
        ///	rect 10 15 300 320
        ///	style WINDOW_STYLE_SHADER
        ///	background &quot;ui/assets/serverinfo_bg.jpg&quot;
        ///	border 1
        ///	bordercolor .5 .5 .5 1
        ///	visible 1
        ///	decoration
        /// [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string serverinfo {
            get {
                return ResourceManager.GetString("serverinfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die #include &quot;ui/menudef.h&quot;
        ///{
        ///
        ////*	INGAME_SELECT_TEAM
        ///Revised by woekele, for 4.0. Slight adjustments, nothing big.
        ///*/
        ///
        ///\\ SETUP MENU \\
        ///
        ///menuDef {
        ///    	name &quot;setup_menu&quot;
        ///    	visible 0
        ///    	fullscreen 1
        ///    	rect 0 0 640 480
        ///	background &quot;ui/assets/ut_menuback.jpg&quot;
        ///    	focusColor 1 1 1 1
        ///    	style 1
        ///    	border 1
        ///	onEsc { close setup_menu ; open main }
        ///
        ///// BLACK TOP BAR    //
        ///itemDef {
        ///	name window
        ///	rect -5 -6 650 76	
        ///	style 1
        ///	border 0
        ///	backcolor 0 0 0 1
        ///	border 1
        ///	bordercolor .5 . [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string setup {
            get {
                return ResourceManager.GetString("setup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die #include &quot;ui/menudef.h&quot;
        ///{
        ///\\ QUIT CREDIT \\
        ///  menuDef {
        ///    	name &quot;specialcredit&quot;
        ///    	visible 0
        ///    	fullscreen 1
        ///    	background &quot;ui/assets/ut_menuback.jpg&quot;
        ///    	focusColor 1 1 1 1
        ///    	style 1
        ///    	border 1
        ///	onEsc { uiScript &quot;quit&quot; }
        ///	onOpen { setitemcolor quit backcolor 0 0 .55 1; setfocus &quot;quit&quot; }
        ///// BLACK TOP BAR    //
        ///itemDef {
        ///	name window
        ///	rect -5 -6 650 76	
        ///	style 1
        ///	border 0
        ///	backcolor 0 0 0 1
        ///	border 1
        ///	bordercolor .5 .5 .5 1
        ///	visible 1
        ///	decoration
        ///	}
        ///// BLACK BOTTOM BAR [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string specialcredit {
            get {
                return ResourceManager.GetString("specialcredit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die #include &quot;ui/menudef.h&quot;
        ///{
        ///
        ////* GAME SYSTEM MENU
        ///Revised by woekele, for 4.0. Removed some useless crap and added usefull stuff.
        ///*/
        ///
        /////Standard Menu Creation
        ///
        ///menuDef {
        ///    name &quot;system_menu&quot;
        ///    visible 0
        ///    fullscreen 0
        ///rect 0 70 490 340
        ///    focusColor 1 1 1 1
        ///    style 1
        ///    border 1
        ///	onOpen { show graphics ; hide sound ; hide network }
        ///	onEsc { close system_menu ; close setup_menu ; open main }
        ///
        ///	itemDef {
        ///		name window
        ///		group grpSystembutton
        ///	rect 10 10 436 313	
        ///		style 1
        ///		bor [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string system {
            get {
                return ResourceManager.GetString("system", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die //
        ///// Team definition is as follows
        ///// 
        ///// English name
        ///// asset name
        ///// 5 team member names ( can be character or aliases or if non-existant, assumed to be human
        ///// 
        ///// Three assets are loaded based on the above asset name
        ///// &quot;asset name&quot; - general branding logo used in the ui and to brand levels
        ///// &quot;asset name_metal&quot; - metal logo for ui
        ///// &quot;asset name_name&quot; - graphic represenation of the name
        /////
        ///teams {
        ///  { &quot;Red&quot; &quot;ui/assets/red&quot; &quot;Athena&quot; }
        ///  { &quot;Blue&quot; &quot;ui/assets/blue&quot; &quot;Athena&quot; }
        ///}
        ///
        ///
        ///// ch [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string teaminfo {
            get {
                return ResourceManager.GetString("teaminfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die #include &quot;ui/menudef.h&quot;
        ///
        ///// Team Score Menu 
        ///{
        ///	menuDef 
        ///	{
        ///    	name &quot;teamscore_menu&quot;
        ///    	visible 0
        ///    	fullscreen 0
        ///    	rect 0 0 640 480
        ///    	focusColor 1 1 1 1
        ///    	style 0
        ///    	border 1
        ///
        ///// GAMETYPE BAR	//
        ///
        ///itemDef {
        ///	name background
        ///	rect 110 10 420 458 
        ///	style WINDOW_STYLE_FILLED
        ///	border 1
        ///	bordercolor .5 .5 .5 1
        ///	forecolor 1 1 1 1
        ///	backcolor 0 0 0 .8
        ///	visible 1
        ///	decoration
        ///	}
        ///
        ///itemDef {
        ///      	name topbar
        ///      	style WINDOW_STYLE_SHADER
        ///      	background &quot;ui/assets/ [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string teamscore {
            get {
                return ResourceManager.GetString("teamscore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die #include &quot;ui/menudef.h&quot;
        ///
        ///{
        ///\\ VID_RESTART POPUP MENU \\
        ///
        ///menuDef {
        ///	name &quot;vid_restart_popmenu&quot;
        ///    	visible 0
        ///    	fullscreen 0
        ///    	//rect 217 200 210 85
        ///	rect 204 122 235 235
        ///	//outOfBoundsClick			// this closes the window if it gets a click out of the rectangle
        ///    	focusColor 1 1 1 1
        ///    	style 1
        ///    	border 1
        ///	popup
        ///	onESC { close vid_restart_popmenu ; 
        ///	open setup_menu ;  
        ///	open system_menu }
        ///
        ///
        ///
        ///itemDef {
        ///	name window
        ///	rect 25 25 185 185
        ///	style 3
        ///	background &quot;ui/assets/quit_p [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string vid_restart {
            get {
                return ResourceManager.GetString("vid_restart", resourceCulture);
            }
        }
        
        internal static byte[] zpak000 {
            get {
                object obj = ResourceManager.GetObject("zpak000", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
